-- Generated from Retool Database schema exports.
-- Core clinical schema only; Retool-specific user-management tables intentionally excluded.
-- PostgreSQL 15+ recommended.

CREATE TYPE "alcohol_enum_58e3c766" AS ENUM ('active', 'former', 'unknown', 'never');
CREATE TYPE "apoe_enum_4069a327" AS ENUM ('not done', 'pending', 'E2E2', 'E2E3', 'E2E4', 'E3E3', 'E3E4', 'E4E4');
CREATE TYPE "aria_type_enum_f672347c" AS ENUM ('ARIA-E', 'ARIA-H', 'ARIA-E + H', 'ABRA', 'Combination', 'none');
CREATE TYPE "autopsy_enum_d73b6252" AS ENUM ('irrelevant', 'not done', 'done', 'done with neuropathology', 'unknown or pending');
CREATE TYPE "caa_criteria_enum_bf701ae9" AS ENUM ('Boston Criteria 1.5', 'Boston Criteria 2.0', 'Edinburgh Criteria', 'Overlapp', 'Unknown', 'Other');
CREATE TYPE "caa_criteria_stage_enum_fc49e696" AS ENUM ('definite (autopsy)', 'probable with supp. pathology', 'probable', 'possible', 'not categorised');
CREATE TYPE "disease_category_enum_2cb9966b" AS ENUM ('intracerebral bleeding', 'ischemic stroke', 'vascular disease', 'cancer', 'other', 'unknown', 'not specified', 'cognitive disorder (dementia)', 'epilepsy', 'transitory neurological episodes (TFNES)', 'metabolic disease', 'arterial hypertension', 'atrial fibrillation');
CREATE TYPE "education_level_enum_7efaf01a" AS ENUM ('none', 'elementary', 'high school', 'college', 'university', 'post-graduate', 'other', 'unknown');
CREATE TYPE "employment_status_enum_9e21aa67" AS ENUM ('active', 'retirement', 'other', 'unknown');
CREATE TYPE "epilepsy_type_enum_5db7ea2f" AS ENUM ('focal seizures', 'generalised seizures', 'other', 'unknown');
CREATE TYPE "gender_enum_5ac919f3" AS ENUM ('woman', 'man', 'other', 'unspecified', 'unknown', '');
CREATE TYPE "hospitalized_where_enum_660d0340" AS ENUM ('cdk', 'other', 'unknown');
CREATE TYPE "location_enum_32c78b5f" AS ENUM ('neck vessels', 'brain', 'heart', 'body', 'abdomen', 'other');
CREATE TYPE "medication_category_enum_1f8daa6a" AS ENUM ('blood pressure control', 'antithrombotic', 'antidiabetic', 'anticoagulant old', 'anticoagulant new', 'beta blocker', 'diuretic', 'cancer medications', 'other', 'unknown');
CREATE TYPE "mri_blood_sequences_enum_08cb699d" AS ENUM ('swi', 'gre', 't2star', 'unknown', 'other');
CREATE TYPE "mri_location_enum_5d3b71eb" AS ENUM ('cdk', 'other', 'unknown');
CREATE TYPE "neck_vessel_result_enum_a1381347" AS ENUM ('ica > 50% right stenosis', 'ica > 50% left stenosis', 'acm right > 50 % stenosis', 'acm left >50% stenosis', 'other cerebral vessel stenosis', 'unknown');
CREATE TYPE "relative_category_enum_6d45e69e" AS ENUM ('first grade', 'second grade', 'unknown', 'not specified', 'Option');
CREATE TYPE "rx_mode_enum_565bcb50" AS ENUM ('ct', 'mri', 'other', 'unknown', 'a ', '');
CREATE TYPE "smoking_enum_01d27a4f" AS ENUM ('active', 'former', 'unknown', 'never');
CREATE TYPE "symptoms_enum_b56e8af4" AS ENUM ('none', 'headache or dizziness', 'focal neurological deficit', 'cognitive decline', 'gait disorder', 'mood change', 'seizures', 'unknown ', 'not specified');
CREATE TYPE "type_enum_3269a85d" AS ENUM ('ultrasound', 'pet ct amyloid', 'pet ct fdg', 'spect', 'mri body', 'other');
CREATE TYPE "type_enum_bf3e5d20" AS ENUM ('lobar', 'basal ganglia', 'subarachnoidal bleeding', 'cmb', 'css', 'other', 'unknown', 'not specified');

CREATE TABLE "case" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "fallnr" TEXT,
    "gender" "gender_enum_5ac919f3",
    "entry_stamp" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "years_of_education" INTEGER DEFAULT 0,
    "education_level" "education_level_enum_7efaf01a",
    "employment_status" "employment_status_enum_9e21aa67",
    "family_history" BOOLEAN DEFAULT FALSE,
    "death_date" DATE DEFAULT CURRENT_DATE,
    "death_cause" TEXT,
    "apoe" "apoe_enum_4069a327",
    "genes" TEXT,
    "smoking" "smoking_enum_01d27a4f",
    "pack_years" INTEGER DEFAULT 0,
    "alcohol" "alcohol_enum_58e3c766",
    "deleted" BOOLEAN DEFAULT FALSE,
    "date_of_birth" DATE DEFAULT CURRENT_DATE,
    "caa_criteria" "caa_criteria_enum_bf701ae9",
    "caa_criteria_stage" "caa_criteria_stage_enum_fc49e696",
    "caa_diagnosis_date" DATE DEFAULT CURRENT_DATE,
    "autopsy" "autopsy_enum_d73b6252" DEFAULT 'irrelevant',
    "data_dumped" BOOLEAN DEFAULT FALSE,
    PRIMARY KEY ("id"),
    CONSTRAINT "case_fallnr_key" UNIQUE ("fallnr")
);

CREATE TABLE "clinical_history" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "case_id" INTEGER,
    "date_disease" DATE DEFAULT CURRENT_DATE,
    "disease" TEXT,
    "hospitalized" BOOLEAN DEFAULT FALSE,
    "date_admissioned" DATE DEFAULT CURRENT_DATE,
    "clinical_outcome" TEXT,
    "mri_field_strength" TEXT DEFAULT '-99',
    "mri_flair" BOOLEAN DEFAULT FALSE,
    "mri_t2" BOOLEAN DEFAULT FALSE,
    "mmse" INTEGER DEFAULT -99,
    "moca" INTEGER DEFAULT -99,
    "rr_systolic" INTEGER DEFAULT -99,
    "rr_diastolic" INTEGER DEFAULT -99,
    "bmi" INTEGER DEFAULT -99,
    "date_discharged" DATE DEFAULT CURRENT_DATE,
    "hospitalized_where" "hospitalized_where_enum_660d0340",
    "disease_category" "disease_category_enum_2cb9966b",
    "rx_mode" "rx_mode_enum_565bcb50",
    "mri_location" "mri_location_enum_5d3b71eb",
    "mri_blood_sequences" "mri_blood_sequences_enum_08cb699d",
    "symptoms" "symptoms_enum_b56e8af4",
    "deleted" BOOLEAN DEFAULT FALSE,
    "epilepsy_type" "epilepsy_type_enum_5db7ea2f",
    "epileptic_status" BOOLEAN DEFAULT FALSE,
    "aria_type" "aria_type_enum_f672347c" DEFAULT 'none',
    PRIMARY KEY ("id")
);

CREATE TABLE "examinations" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "case_id" INTEGER,
    "type" "type_enum_3269a85d",
    "location" "location_enum_32c78b5f",
    "result" TEXT,
    "neck_vessel_result" "neck_vessel_result_enum_a1381347",
    "deleted" BOOLEAN DEFAULT FALSE,
    "date_examination" DATE DEFAULT CURRENT_DATE,
    PRIMARY KEY ("id")
);

CREATE TABLE "family_history" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "case_id" INTEGER,
    "relative" TEXT,
    "disease" TEXT,
    "relative_category" "relative_category_enum_6d45e69e",
    "deleted" BOOLEAN DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE "laboratory" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "case_id" INTEGER,
    "date_of_exam" DATE DEFAULT CURRENT_DATE,
    "csf_beta42" INTEGER DEFAULT 0,
    "csf_beta4240_ratio" INTEGER DEFAULT 0,
    "csf_tau_total" INTEGER DEFAULT 0,
    "csf_ptau_total" INTEGER DEFAULT 0,
    "crp" INTEGER DEFAULT 0,
    "hba1c" INTEGER DEFAULT 0,
    "deleted" BOOLEAN DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE "medications" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "case_id" INTEGER,
    "date_noted" DATE DEFAULT CURRENT_DATE,
    "medication" TEXT,
    "date_stopped" DATE DEFAULT CURRENT_DATE,
    "medication_category" "medication_category_enum_1f8daa6a",
    "deleted" BOOLEAN DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE "radiology" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "case_id" INTEGER,
    "acute_lesion" BOOLEAN DEFAULT FALSE,
    "type" "type_enum_bf3e5d20",
    "deleted" BOOLEAN DEFAULT FALSE,
    "mri_date" DATE DEFAULT CURRENT_DATE,
    "pid" TEXT,
    "saved_on_hdd" BOOLEAN DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE "states" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "field" TEXT,
    "state" TEXT,
    PRIMARY KEY ("id")
);

ALTER TABLE "clinical_history" ADD CONSTRAINT "clinica_history_case_id_fkey" FOREIGN KEY ("case_id") REFERENCES "case" ("id");
ALTER TABLE "examinations" ADD CONSTRAINT "examinations_case_id_fkey" FOREIGN KEY ("case_id") REFERENCES "case" ("id");
ALTER TABLE "family_history" ADD CONSTRAINT "family_history_case_id_fkey" FOREIGN KEY ("case_id") REFERENCES "case" ("id");
ALTER TABLE "laboratory" ADD CONSTRAINT "laboratory_case_id_fkey" FOREIGN KEY ("case_id") REFERENCES "case" ("id");
ALTER TABLE "medications" ADD CONSTRAINT "medications_case_id_fkey" FOREIGN KEY ("case_id") REFERENCES "case" ("id");
ALTER TABLE "radiology" ADD CONSTRAINT "radiology_case_id_fkey" FOREIGN KEY ("case_id") REFERENCES "case" ("id");

CREATE INDEX "ix_clinical_history_case_id" ON "clinical_history" ("case_id");
CREATE INDEX "ix_examinations_case_id" ON "examinations" ("case_id");
CREATE INDEX "ix_family_history_case_id" ON "family_history" ("case_id");
CREATE INDEX "ix_laboratory_case_id" ON "laboratory" ("case_id");
CREATE INDEX "ix_medications_case_id" ON "medications" ("case_id");
CREATE INDEX "ix_radiology_case_id" ON "radiology" ("case_id");

CREATE TABLE "source_documents" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "filename" TEXT NOT NULL,
    "sha256" TEXT NOT NULL UNIQUE,
    "file_size_bytes" BIGINT,
    "parser" TEXT,
    "parser_version" TEXT,
    "document_json" JSONB,
    "imported_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "extraction_runs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "source_document_id" BIGINT NOT NULL REFERENCES "source_documents" ("id") ON DELETE CASCADE,
    "model_name" TEXT NOT NULL,
    "model_version" TEXT,
    "prompt_version" TEXT,
    "status" TEXT NOT NULL,
    "started_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completed_at" TIMESTAMPTZ,
    "raw_output" JSONB,
    "validation_errors" JSONB
);

CREATE INDEX "ix_extraction_runs_source_document_id" ON "extraction_runs" ("source_document_id");
