"""Create identifier-only cases from imported source-document patient IDs."""
import argparse
from dataclasses import asdict, dataclass
import json

from sqlalchemy import inspect, text
from sqlalchemy.dialects.postgresql import insert

from .extraction.case_resolver import CaseResolutionError


class BootstrapSchemaError(ValueError):
    pass


@dataclass
class CaseBootstrapResult:
    patient_id: str
    fallnr: str
    case_id: int | None
    created: bool
    would_create: bool = False


def inspect_case_schema(session):
    inspector = inspect(session.connection())
    columns = inspector.get_columns("case", schema="public")
    # format_type reports native enum names and timestamptz accurately.
    types = dict(session.execute(text("""
        SELECT a.attname, format_type(a.atttypid, a.atttypmod)
        FROM pg_attribute a
        WHERE a.attrelid = 'public.case'::regclass
          AND a.attnum > 0 AND NOT a.attisdropped
    """)).all())
    unique = inspector.get_unique_constraints("case", schema="public")
    indexes = inspector.get_indexes("case", schema="public")
    fallnr_unique = any(c["column_names"] == ["fallnr"] for c in unique) or any(
        i.get("unique") and i.get("column_names") == ["fallnr"]
        and not i.get("dialect_options", {}).get("postgresql_where") for i in indexes)
    required = [c["name"] for c in columns if not c["nullable"]
                and c["name"] not in ("id", "fallnr")
                and not (c["name"] == "entry_stamp" and c.get("default"))]
    id_column = next(c for c in columns if c["name"] == "id")
    generated_id = bool(id_column.get("identity") or "nextval(" in (id_column.get("default") or ""))
    return {"columns": [{"name": c["name"], "type": types[c["name"]],
                         "nullable": c["nullable"], "default": c.get("default"),
                         "identity": c.get("identity")} for c in columns],
            "unique_constraints": unique, "fallnr_unique": fallnr_unique,
            "generated_id": generated_id, "required_fields": required}


def validate_schema(schema):
    if schema["required_fields"]:
        raise BootstrapSchemaError("REQUIRED_CASE_FIELDS: " + ", ".join(schema["required_fields"]))
    if not schema["generated_id"]:
        raise BootstrapSchemaError("CASE_ID_NOT_AUTOGENERATED")
    if not schema["fallnr_unique"]:
        raise BootstrapSchemaError("FALLNR_UNIQUE_REQUIRED")


def imported_patient_ids(session):
    columns = inspect(session.connection()).get_columns("source_documents", schema="public")
    direct = any(c["name"] == "patient_id" for c in columns)
    expression = "patient_id" if direct else "document_json->'document'->>'patient_id'"
    invalid = session.scalar(text(f"SELECT count(*) FROM public.source_documents WHERE "
                                  f"{expression} IS NULL OR btrim({expression}) = ''"))
    if invalid:
        raise ValueError("SOURCE_DOCUMENT_PATIENT_ID_MISSING")
    return list(session.scalars(text(f"SELECT DISTINCT {expression} AS patient_id "
                                     "FROM public.source_documents ORDER BY patient_id")))


def _get_or_create(patient_id, commit, session, schema):
    if not isinstance(patient_id, str) or not patient_id.strip():
        raise ValueError("patient_id must be a nonempty string")
    matches = session.execute(text('SELECT id FROM public."case" WHERE fallnr = :patient_id'),
                              {"patient_id": patient_id}).all()
    if len(matches) > 1:
        raise CaseResolutionError("CASE_AMBIGUOUS")
    if matches:
        return CaseBootstrapResult(patient_id, patient_id, matches[0][0], False)
    if not commit:
        return CaseBootstrapResult(patient_id, patient_id, None, False, True)
    from .database.models import Case
    # Explicit NULL overrides all nullable clinical/demographic defaults.
    values = {c["name"]: None for c in schema["columns"]
              if c["nullable"] and c["name"] not in ("id", "fallnr")}
    values["fallnr"] = patient_id
    statement = insert(Case).values(**values).on_conflict_do_nothing(
        index_elements=["fallnr"]).returning(Case.id)
    case_id = session.scalar(statement)
    if case_id is not None:
        return CaseBootstrapResult(patient_id, patient_id, case_id, True)
    # A concurrent bootstrap inserted this patient after our initial lookup.
    matches = session.execute(text('SELECT id FROM public."case" WHERE fallnr = :patient_id'),
                              {"patient_id": patient_id}).all()
    if len(matches) != 1:
        raise CaseResolutionError("CASE_AMBIGUOUS" if matches else "CASE_NOT_FOUND")
    return CaseBootstrapResult(patient_id, patient_id, matches[0][0], False)


def get_or_create_case_for_patient(patient_id: str, commit: bool = False, *, session_factory=None):
    from .database import SessionLocal
    factory = session_factory or SessionLocal
    with (factory.begin() if commit else factory()) as session:
        schema = inspect_case_schema(session)
        validate_schema(schema)
        return _get_or_create(patient_id, commit, session, schema)


def bootstrap_cases(commit=False, *, patient_id=None, session_factory=None):
    from .database import SessionLocal
    factory = session_factory or SessionLocal
    with (factory.begin() if commit else factory()) as session:
        schema = inspect_case_schema(session)
        validate_schema(schema)
        patients = imported_patient_ids(session)
        if patient_id is not None:
            if patient_id not in patients:
                raise ValueError("PATIENT_NOT_IMPORTED")
            patients = [patient_id]
        # Preflight every identifier before any case inserts.
        planned = []
        ambiguous = 0
        for patient in patients:
            try:
                planned.append(_get_or_create(patient, False, session, schema))
            except CaseResolutionError:
                ambiguous += 1
        summary = {"patients_found": len(patients),
                   "existing_cases": sum(r.case_id is not None for r in planned),
                   "cases_to_create": sum(r.would_create for r in planned),
                   "ambiguous_cases": ambiguous, "errors": []}
        if ambiguous:
            summary["errors"] = ["CASE_AMBIGUOUS"]
            return summary, []
        results = [_get_or_create(patient, True, session, schema) for patient in patients] if commit else planned
        return summary, results


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--dry-run", action="store_true")
    mode.add_argument("--commit", action="store_true")
    parser.add_argument("--patient", help="Restrict to one imported patient")
    args = parser.parse_args(argv)
    try:
        summary, results = bootstrap_cases(args.commit, patient_id=args.patient)
        report = summary if not args.commit else {
            **summary, "cases_created": sum(r.created for r in results),
            "results": [asdict(r) for r in results]}
    except (BootstrapSchemaError, ValueError) as exc:
        print(json.dumps({"patients_found": 0, "existing_cases": 0, "cases_to_create": 0,
                          "ambiguous_cases": 0, "errors": [str(exc)]}, indent=2))
        return 1
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return int(bool(summary["errors"]))


if __name__ == "__main__":
    raise SystemExit(main())
